name: gdg_organizers_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  advanced_search: ^2.2.3
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  flame: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: null
  flutter_rating_stars: ^1.0.3+4
  flutter_secure_storage: ^7.0.1
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  iconsax: ^0.0.8
  image_picker: ^0.8.6+1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  lite_rolling_switch: ^1.0.0
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  socket_io_client: ^2.0.1

flutter_native_splash:
  color: "#4285f4"

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: "^0.11.0"

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
