// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWH2S8r8pI1AxgAAcmS-DA4YKKPkjmIvw',
    appId: '1:154731306770:web:5fc47232e7aa4fe5a61dcb',
    messagingSenderId: '154731306770',
    projectId: 'gdg-organizers-app',
    authDomain: 'gdg-organizers-app.firebaseapp.com',
    storageBucket: 'gdg-organizers-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8e4_DD8M8F5a-_5FY0LZS6AWjIXDCGq4',
    appId: '1:154731306770:android:12071e656114d127a61dcb',
    messagingSenderId: '154731306770',
    projectId: 'gdg-organizers-app',
    storageBucket: 'gdg-organizers-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSHKzWalHnhpI8covpKpJ1g9iBwkXZSX4',
    appId: '1:154731306770:ios:f6a11973d493e3f1a61dcb',
    messagingSenderId: '154731306770',
    projectId: 'gdg-organizers-app',
    storageBucket: 'gdg-organizers-app.appspot.com',
    iosClientId: '154731306770-srgbsdgfda9hkiq15bulsdavva1c2ks4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdgOrganizersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSHKzWalHnhpI8covpKpJ1g9iBwkXZSX4',
    appId: '1:154731306770:ios:f6a11973d493e3f1a61dcb',
    messagingSenderId: '154731306770',
    projectId: 'gdg-organizers-app',
    storageBucket: 'gdg-organizers-app.appspot.com',
    iosClientId: '154731306770-srgbsdgfda9hkiq15bulsdavva1c2ks4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdgOrganizersApp',
  );
}
